config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # resources :movies

  resources :lists do
    resources :bookmarks, only: [:create, :destroy, :new]
  end

  resources :movies do
    resources :bookmarks, only: [:create, :destroy, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  # Validates the presence of a movie and a list for the bookmark
  validates :movie_id, presence: true
  validates :list_id, presence: true

  # Ensures [movie, list] pairings are unique
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates :overview, presence: true
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list

  def new

    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @list.bookmarks.new(bookmark_params)
    @bookmark.list = @list

    # raise
    if @bookmark.save
      redirect_to @list, notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark = @list.bookmarks.find(params[:id])
    @bookmark.destroy
    # raise
    redirect_to list_path(@list), notice: 'Bookmark was successfully deleted.'
  end


  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    # raise
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to list_path(@list), notice: 'List was successfully created.'
    else
      render :new # Render the 'new' view again if the list can't be saved
    end
  end

  private

  def params_list
    params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<h3>For  <%= @list.name %></h3>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, collection: Movie.all, prompt: "Select a Movie" %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>
<%= link_to "Go back to list", list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <%=javascript_importmap_tags%>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
    </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <p class="nav-link active"><%= link_to "My lists", lists_path %></p>

              </li>
              <li class="nav-item">
                <p class="nav-link"><%= link_to "Create new list", new_list_path %></p>
              </li>
          </ul>
        </div>
      </div>
    </div>
     <div class="banner" style="background-image: url('<%= asset_path 'image.jpg' %>');">
      <div class="container">
        <h1 style = "text-align: center;" >Save movies</h1>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Index List</h1>
<ul>
<% @lists.each do |list| %>
  <li><%= link_to list.name, list_path(list) %></li>
<% end %>
</ul>

<%= link_to "new_list", new_list_path %>

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  Breakfast
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Create List", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1>Show List</h1>
<p><%= @list.name %> </p>

<ul>
<% @list.bookmarks.each do |bookmark| %>
  <li><%= bookmark.comment%> - <%= bookmark.movie.title %> - <%= bookmark.list.name %> -  <%= link_to 'Delete', list_bookmark_path(@list, bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
<% end %>
</ul>
<%= link_to "Go back to list Index", lists_path %>
<p>.</p>
<%= link_to "create bookmark", new_list_bookmark_path(@list)%>